name = "DigitLLComms"
uuid = "037fdb33-3b16-4ef5-a139-af2d43bd5761"
authors = ["Alphonsus Adu-Bredu"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
