[world.doorway.top]
type = "box"
size = [0.2, 0.76, 0.02]
pose = {xyz = [0, 0, 1.54]}
color = "#FFFFFF"

[world.doorway.shelf1]
parent = "top"
type = "box"
size = [0.2, 0.76, 0.02]
pose = {xyz = [0, 0, -0.34]}
color = "#FFFFFF"

[world.doorway.bottle1]
parent = "shelf1"
type = "cylinder"
size = [0.025, 0.1]
pose = {xyz = [0, 0.15, 0.05]}
color = "#0000FF"

[world.doorway.shelf2]
parent = "top"
type = "box"
size = [0.2, 0.76, 0.02]
pose = {xyz = [0, 0, -0.69]} 
color = "#FFFFFF"

[world.doorway.bottle2]
parent = "shelf2"
type = "cylinder"
size = [0.025, 0.1]
pose = {xyz = [0, -0.15, 0.05]}
color = "#FF0000"


[world.doorway.shelf3]
parent = "top"
type = "box"
size = [0.2, 0.76, 0.02]
pose = {xyz = [0, 0, -1.0]} 
color = "#FFFFFF"

[world.doorway.shelfbottom]
parent = "top"
type = "box"
size = [0.2, 0.76, 0.02]
pose = {xyz = [0, 0, -1.52]} 
color = "#FFFFFF"

[world.doorway.left]
parent = "top"
type = "box"
size = [0.2, 0.02, 1.54]
pose = {xyz = [0, -0.38, -0.77]}
color = "#FFFFFF"

[world.doorway.right]
parent = "top"
type = "box"
size = [0.2, 0.02, 1.54]
pose = {xyz = [0, 0.38, -0.77]}
color = "#FFFFFF"

[world.table.top]
type = "box"
size = [0.4, 0.8, 0.02]
pose = {xyz = [0, 0, 0.8]}
color = "#000000"

[world.table.bottle3]
parent = "top"
type = "cylinder"
size = [0.025, 0.1]
pose = {xyz = [-0.1, -0.15, 0.05]}
color = "#00FF00"


[world.table.leg1]
parent = "top"
type = "box"
size = [0.05, 0.05, 0.78]
pose = {xyz = [0.18, 0.38, -0.39]}
color = "#000000"

[world.table.leg2]
parent = "top"
type = "box"
size = [0.05, 0.05, 0.78]
pose = {xyz = [0.18, -0.38, -0.39]}
color = "#000000"

[world.table.leg3]
parent = "top"
type = "box"
size = [0.05, 0.05, 0.78]
pose = {xyz = [-0.18, 0.38, -0.39]}
color = "#000000"

[world.table.leg4]
parent = "top"
type = "box"
size = [0.05, 0.05, 0.78]
pose = {xyz = [-0.18, -0.38, -0.39]}
color = "#000000"

# Models in the scene
[[model-list]]
model = "robot"
pose = {xyz = [0, 0, 1]}

[[model-list]]
model = "doorway"
pose = {xy = [3, 0]}
fixed = true
 
 [[model-list]]
 model = "table"
 pose = {rpyxyz = [0.0, 0.0, 1.5707, 0.0, 2.0, 0.0]}
 fixed = true