########################################################################
# Complete model reference
########################################################################

# Each body in a model is a separate table under the 'world' table in the
# configuration. One body in each model must be the root body, which does
# not have a parent body.
[world.example-model.body-a] 
parent = "" 
type = "box" 
size = [1, 0.9, 0.2] 
pose = {xyz = [0, 0, 0.1]} 
mass = 3  
friction = [0.5, 0.005, 0.0001] 
color = "MediumAquaMarine" 
# april-tags = [{id = 3, pose = {xyz = [0.5, 0, 0]}},
#               {id = 4, pose = {xyz = [0, 0, 0.1]}}] 

[world.example-model.body-b]
parent = "body-a"
type = "box"
size = [1, 0.3, 0.2]
pose = {xyz = [0, 0, 0.2]}
mass = 1 
joint.type = "revolute" 
joint.offset = [0, 0, 0] 
joint.limits = [0, 180] 
joint.axis = [0, 0, 1] 
joint.damping = 0.1 
joint.friction = 0.1



[[model-list]]
model = "example-model" 
id = 555 
pose = {axyd = [-45, 1, 0.5]} 
fixed = false 
# april-tag-id-offset = 10 
color = "#F08080"

[[model-list]]
model = "example-model"
pose = {xy = [1, -1]}
fixed = true

[[model-list]]
model = "robot"
pose = {xyz = [-1, 0, 1]}