########################################################################
# Complete model reference
########################################################################

# Each body in a model is a separate table under the 'world' table in the
# configuration. One body in each model must be the root body, which does
# not have a parent body.
[world.obstacle.body] 
parent = ""
type = "sphere" 
size = 0.125 
pose = {xyz = [0, 0, 0.1]} 
mass = 0.1 
friction = [0.5, 0.005, 0.0001] 
color = "#382d2d" 
# april-tags = [{id = 3, pose = {xyz = [0.5, 0, 0]}},
#               {id = 4, pose = {xyz = [0, 0, 0.1]}}]



[[model-list]] 
model = "obstacle" 
id = 555  
pose = {xyz = [3, 0, 3]} 
fixed = false 

[[model-list]] 
model = "obstacle" 
id = 556
pose = {xyz = [-3, 0, 3]} 
fixed = true 

[[model-list]]
model = "robot"
pose = {xyz = [0, 0, 1]}
